<?php

namespace Database\Seeders;

use App\Models\MaintenanceCategory;
use App\Models\MaintenanceType;
use Illuminate\Database\Seeder;

class MaintenanceTypeSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'Motor' => [
                ['name' => 'Troca de Óleo do Motor', 'recommended_interval_km' => 10000, 'recommended_interval_months' => 12],
                ['name' => 'Troca de Filtro de Óleo', 'recommended_interval_km' => 10000, 'recommended_interval_months' => 12],
                ['name' => 'Troca de Filtro de Ar', 'recommended_interval_km' => 20000, 'recommended_interval_months' => 24],
                ['name' => 'Troca de Filtro de Combustível', 'recommended_interval_km' => 40000, 'recommended_interval_months' => 24],
                ['name' => 'Troca de Velas', 'recommended_interval_km' => 60000, 'recommended_interval_months' => 36],
                ['name' => 'Troca de Cabos de Velas'],
                ['name' => 'Limpeza de Bicos Injetores', 'recommended_interval_km' => 50000, 'recommended_interval_months' => 24],
                ['name' => 'Troca de Correia Dentada', 'recommended_interval_km' => 60000, 'recommended_interval_months' => 60],
                ['name' => 'Troca de Correia Auxiliar'],
                ['name' => 'Troca de Tensor da Correia'],
                ['name' => 'Troca de Corrente de Comando'],
                ['name' => 'Troca da Junta do Cabeçote'],
                ['name' => 'Retífica de Motor'],
                ['name' => 'Regulagem de Válvulas'],
                ['name' => 'Limpeza do Corpo de Borboleta'],
                ['name' => 'Troca de Coxim do Motor'],
                ['name' => 'Troca de Bomba de Óleo'],
                ['name' => 'Troca de Bomba de Água', 'recommended_interval_km' => 100000, 'recommended_interval_months' => 60],
                ['name' => 'Troca de Retentor do Virabrequim'],
                ['name' => 'Troca de Retentor de Comando'],
            ],
            'Sistema de Arrefecimento' => [
                ['name' => 'Troca de Aditivo do Radiador', 'recommended_interval_km' => 40000, 'recommended_interval_months' => 24],
                ['name' => 'Limpeza do Radiador'],
                ['name' => 'Troca de Radiador'],
                ['name' => 'Troca de Mangueira do Radiador'],
                ['name' => 'Troca de Reservatório'],
                ['name' => 'Troca de Tampa do Reservatório'],
                ['name' => 'Troca de Ventoinha'],
                ['name' => 'Troca de Sensor de Temperatura'],
                ['name' => 'Troca de Válvula Termostática'],
                ['name' => 'Troca de Bomba d\'Água'],
            ],
            'Freios' => [
                ['name' => 'Troca de Pastilhas de Freio', 'recommended_interval_km' => 30000, 'recommended_interval_months' => 24],
                ['name' => 'Troca de Discos de Freio'],
                ['name' => 'Troca de Lonas de Freio'],
                ['name' => 'Troca de Tambor de Freio'],
                ['name' => 'Troca de Fluido de Freio', 'recommended_interval_km' => 40000, 'recommended_interval_months' => 24],
                ['name' => 'Sangria do Sistema de Freio'],
                ['name' => 'Troca de Cilindro Mestre'],
                ['name' => 'Troca de Cilindro de Roda'],
                ['name' => 'Troca de Servo Freio'],
                ['name' => 'Troca de Flexível de Freio'],
                ['name' => 'Troca de Pinça de Freio'],
                ['name' => 'Retífica de Disco de Freio'],
            ],
            'Suspensão' => [
                ['name' => 'Troca de Amortecedores'],
                ['name' => 'Troca de Molas'],
                ['name' => 'Troca de Buchas da Suspensão'],
                ['name' => 'Troca de Bieletas'],
                ['name' => 'Troca de Bandejas'],
                ['name' => 'Troca de Pivôs'],
                ['name' => 'Troca de Coxins do Amortecedor'],
                ['name' => 'Troca de Batentes'],
                ['name' => 'Regulagem de Suspensão'],
                ['name' => 'Troca de Terminal de Direção'],
            ],
            'Direção' => [
                ['name' => 'Troca da Caixa de Direção'],
                ['name' => 'Troca da Bomba de Direção Hidráulica'],
                ['name' => 'Troca de Fluido de Direção'],
                ['name' => 'Troca de Braço Axial'],
                ['name' => 'Troca de Articulação Axial'],
                ['name' => 'Troca de Terminal de Direção'],
                ['name' => 'Regulagem da Direção'],
                ['name' => 'Troca da Coluna de Direção'],
            ],
            'Pneus' => [
                ['name' => 'Troca de Pneus'],
                ['name' => 'Rodízio de Pneus', 'recommended_interval_km' => 10000, 'recommended_interval_months' => 6],
                ['name' => 'Alinhamento', 'recommended_interval_km' => 10000, 'recommended_interval_months' => 6],
                ['name' => 'Balanceamento', 'recommended_interval_km' => 10000, 'recommended_interval_months' => 6],
                ['name' => 'Conserto de Pneu (Borracharia)'],
                ['name' => 'Recauchutagem'],
                ['name' => 'Calibragem de Pneus'],
            ],
            'Transmissão' => [
                ['name' => 'Troca de Embreagem'],
                ['name' => 'Troca de Kit de Embreagem'],
                ['name' => 'Troca de Óleo do Câmbio', 'recommended_interval_km' => 60000, 'recommended_interval_months' => 36],
                ['name' => 'Troca de Retentor do Câmbio'],
                ['name' => 'Troca de Semi-eixos'],
                ['name' => 'Troca de Coifa do Semi-eixo'],
                ['name' => 'Troca de Diferencial'],
                ['name' => 'Reparo no Câmbio'],
            ],
            'Sistema Elétrico' => [
                ['name' => 'Troca da Bateria'],
                ['name' => 'Troca do Alternador'],
                ['name' => 'Troca do Motor de Arranque'],
                ['name' => 'Troca do Regulador de Tensão'],
                ['name' => 'Diagnóstico de Partida'],
                ['name' => 'Reparo no Chicote Elétrico'],
                ['name' => 'Troca de Fusíveis'],
                ['name' => 'Troca de Relés'],
                ['name' => 'Troca de Comutador de Ignição'],
            ],
            'Iluminação' => [
                ['name' => 'Troca de Farol'],
                ['name' => 'Troca de Lanterna'],
                ['name' => 'Troca de Lâmpada de Farol'],
                ['name' => 'Troca de Lâmpada de Lanterna'],
                ['name' => 'Troca de Lâmpada de Seta'],
                ['name' => 'Polimento de Farol'],
                ['name' => 'Troca de Farol de Milha'],
                ['name' => 'Troca de Luz de LED'],
                ['name' => 'Troca de Luz de Xenon'],
                ['name' => 'Troca de Luz de Freio'],
                ['name' => 'Troca de Luz de Ré'],
                ['name' => 'Troca de Luz de Placa'],
            ],
            'Ar Condicionado' => [
                ['name' => 'Carga de Gás do Ar Condicionado'],
                ['name' => 'Troca do Filtro de Cabine', 'recommended_interval_km' => 20000, 'recommended_interval_months' => 12],
                ['name' => 'Troca do Compressor'],
                ['name' => 'Troca do Condensador'],
                ['name' => 'Troca do Evaporador'],
                ['name' => 'Troca da Válvula Expansora'],
                ['name' => 'Troca da Correia do Compressor'],
                ['name' => 'Limpeza do Sistema de Ar Condicionado'],
                ['name' => 'Troca do Ventilador da Caixa Evaporadora'],
            ],
            'Sistema de Combustível' => [
                ['name' => 'Troca da Bomba de Combustível'],
                ['name' => 'Troca do Bico Injetor'],
                ['name' => 'Limpeza de Bico Injetor'],
                ['name' => 'Troca da Flauta de Combustível'],
                ['name' => 'Troca da Mangueira de Combustível'],
                ['name' => 'Troca da Tampa do Tanque'],
                ['name' => 'Limpeza do Tanque de Combustível'],
                ['name' => 'Troca do Regulador de Pressão'],
            ],
            'Escapamento' => [
                ['name' => 'Troca do Catalisador'],
                ['name' => 'Troca do Silencioso Dianteiro'],
                ['name' => 'Troca do Silencioso Traseiro'],
                ['name' => 'Troca do Intermediário'],
                ['name' => 'Troca da Sonda Lambda'],
                ['name' => 'Troca da Junta do Escapamento'],
                ['name' => 'Solda no Escapamento'],
                ['name' => 'Troca do Tubo de Escapamento'],
            ],
            'Lataria e Pintura' => [
                ['name' => 'Polimento'],
                ['name' => 'Polimento Técnico'],
                ['name' => 'Cristalização de Pintura'],
                ['name' => 'Martelinho de Ouro'],
                ['name' => 'Funilaria'],
                ['name' => 'Pintura Completa'],
                ['name' => 'Pintura de Para-choque'],
                ['name' => 'Pintura de Porta'],
                ['name' => 'Aplicação de PPF (Paint Protection Film)'],
                ['name' => 'Aplicação de Ceramic Coating'],
                ['name' => 'Remoção de Arranhões'],
            ],
            'Vidros' => [
                ['name' => 'Troca do Para-brisa'],
                ['name' => 'Troca do Vidro Lateral'],
                ['name' => 'Troca do Vidro Traseiro'],
                ['name' => 'Troca do Motor do Vidro Elétrico'],
                ['name' => 'Troca da Máquina de Vidro'],
                ['name' => 'Troca do Botão do Vidro Elétrico'],
                ['name' => 'Reparo de Trinca no Para-brisa'],
            ],
            'Limpadores' => [
                ['name' => 'Troca das Palhetas do Limpador', 'recommended_interval_km' => 10000, 'recommended_interval_months' => 12],
                ['name' => 'Troca do Motor do Limpador'],
                ['name' => 'Troca da Transmissão do Limpador'],
                ['name' => 'Troca do Braço do Limpador'],
                ['name' => 'Troca do Esguicho do Limpador'],
                ['name' => 'Troca do Reservatório de Água do Limpador'],
            ],
            'Acessórios' => [
                ['name' => 'Instalação de Alarme'],
                ['name' => 'Instalação de Rastreador'],
                ['name' => 'Instalação de Sensor de Ré'],
                ['name' => 'Instalação de Câmera de Ré'],
                ['name' => 'Instalação de Multimídia'],
                ['name' => 'Instalação de Subwoofer'],
                ['name' => 'Instalação de Insulfilm'],
                ['name' => 'Instalação de Engate'],
                ['name' => 'Instalação de Capota Marítima'],
                ['name' => 'Instalação de Rack de Teto'],
                ['name' => 'Troca de Maçanetas Cromadas'],
                ['name' => 'Instalação de Farol de Milha'],
                ['name' => 'Instalação de Luz de LED'],
            ],
            'Revisões' => [
                ['name' => 'Revisão de 10.000 km', 'recommended_interval_km' => 10000, 'recommended_interval_months' => 6],
                ['name' => 'Revisão de 20.000 km', 'recommended_interval_km' => 20000, 'recommended_interval_months' => 12],
                ['name' => 'Revisão de 30.000 km', 'recommended_interval_km' => 30000, 'recommended_interval_months' => 18],
                ['name' => 'Revisão de 40.000 km', 'recommended_interval_km' => 40000, 'recommended_interval_months' => 24],
                ['name' => 'Revisão de 50.000 km', 'recommended_interval_km' => 50000, 'recommended_interval_months' => 30],
                ['name' => 'Revisão de 60.000 km', 'recommended_interval_km' => 60000, 'recommended_interval_months' => 36],
                ['name' => 'Revisão de 70.000 km', 'recommended_interval_km' => 70000, 'recommended_interval_months' => 42],
                ['name' => 'Revisão de 80.000 km', 'recommended_interval_km' => 80000, 'recommended_interval_months' => 48],
                ['name' => 'Revisão de 90.000 km', 'recommended_interval_km' => 90000, 'recommended_interval_months' => 54],
                ['name' => 'Revisão de 100.000 km', 'recommended_interval_km' => 100000, 'recommended_interval_months' => 60],
                ['name' => 'Revisão Preventiva'],
                ['name' => 'Revisão Corretiva'],
                ['name' => 'Revisão Completa'],
            ],
            'Documentação' => [
                ['name' => 'Licenciamento'],
                ['name' => 'IPVA'],
                ['name' => 'Seguro'],
                ['name' => 'Renovação de Seguro'],
                ['name' => 'Vistoria'],
                ['name' => 'Transferência'],
                ['name' => 'Emplacamento'],
            ],
            'Serviços Gerais' => [
                ['name' => 'Diagnóstico Computadorizado'],
                ['name' => 'Inspeção Geral'],
                ['name' => 'Check-up Veicular'],
                ['name' => 'Guincho'],
                ['name' => 'Socorro Mecânico'],
                ['name' => 'Lavagem Técnica'],
                ['name' => 'Higienização Interna'],
                ['name' => 'Desinfecção'],
                ['name' => 'Outro Serviço'],
            ],
            'Veículos Elétricos' => [
                ['name' => 'Diagnóstico da Bateria de Tração'],
                ['name' => 'Balanceamento de Células da Bateria'],
                ['name' => 'Troca do Módulo da Bateria'],
                ['name' => 'Substituição da Bateria de Tração'],
                ['name' => 'Atualização de Firmware da Bateria'],
                ['name' => 'Atualização de Software do Veículo'],
                ['name' => 'Diagnóstico do Inversor'],
                ['name' => 'Substituição do Inversor'],
                ['name' => 'Diagnóstico do Motor Elétrico'],
                ['name' => 'Substituição do Motor Elétrico'],
                ['name' => 'Inspeção do Sistema de Alta Tensão'],
                ['name' => 'Troca do Fluido de Arrefecimento da Bateria'],
                ['name' => 'Inspeção dos Cabos de Alta Tensão'],
                ['name' => 'Troca do Carregador Embarcado'],
                ['name' => 'Reparo do Conector de Recarga'],
                ['name' => 'Troca da Porta de Carregamento'],
                ['name' => 'Diagnóstico do Sistema Regenerativo'],
                ['name' => 'Manutenção Preventiva do Sistema Elétrico'],
                ['name' => 'Inspeção do Sistema de Gerenciamento da Bateria (BMS)'],
                ['name' => 'Calibração do Sistema de Bateria'],
            ],
            'Veículos Híbridos' => [
                ['name' => 'Diagnóstico do Sistema Híbrido'],
                ['name' => 'Inspeção da Bateria Híbrida'],
                ['name' => 'Troca da Bateria Híbrida'],
                ['name' => 'Diagnóstico do Motor Elétrico Auxiliar'],
                ['name' => 'Diagnóstico do Sistema de Regeneração'],
                ['name' => 'Atualização de Software Híbrido'],
                ['name' => 'Inspeção de Conversores'],
                ['name' => 'Inspeção do Sistema de Alta Tensão'],
                ['name' => 'Calibração do Sistema Híbrido'],
            ],
        ];

        foreach ($data as $categoryName => $types) {
            $category = MaintenanceCategory::where('name', $categoryName)->first();

            if (! $category) {
                continue;
            }

            foreach ($types as $type) {
                MaintenanceType::updateOrCreate(
                    [
                        'maintenance_category_id' => $category->id,
                        'name' => $type['name'],
                    ],
                    [
                        'description' => $type['description'] ?? null,
                        'recommended_interval_km' => $type['recommended_interval_km'] ?? null,
                        'recommended_interval_months' => $type['recommended_interval_months'] ?? null,
                        'active' => true,
                    ]
                );
            }
        }
    }
}
